(cl:defpackage beam_test-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "BEAM"
   "<BEAM-REQUEST>"
   "BEAM-REQUEST"
   "<BEAM-RESPONSE>"
   "BEAM-RESPONSE"
   "MULTIPLY"
   "<MULTIPLY-REQUEST>"
   "MULTIPLY-REQUEST"
   "<MULTIPLY-RESPONSE>"
   "MULTIPLY-RESPONSE"
  ))

