// Generated by gencpp from file test2/Beam.msg
// DO NOT EDIT!


#ifndef TEST2_MESSAGE_BEAM_H
#define TEST2_MESSAGE_BEAM_H

#include <ros/service_traits.h>


#include <test2/BeamRequest.h>
#include <test2/BeamResponse.h>


namespace test2
{

struct Beam
{

typedef BeamRequest Request;
typedef BeamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Beam
} // namespace test2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test2::Beam > {
  static const char* value()
  {
    return "f776d2a85589bd6653da0466ec4b2203";
  }

  static const char* value(const ::test2::Beam&) { return value(); }
};

template<>
struct DataType< ::test2::Beam > {
  static const char* value()
  {
    return "test2/Beam";
  }

  static const char* value(const ::test2::Beam&) { return value(); }
};


// service_traits::MD5Sum< ::test2::BeamRequest> should match
// service_traits::MD5Sum< ::test2::Beam >
template<>
struct MD5Sum< ::test2::BeamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test2::Beam >::value();
  }
  static const char* value(const ::test2::BeamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test2::BeamRequest> should match
// service_traits::DataType< ::test2::Beam >
template<>
struct DataType< ::test2::BeamRequest>
{
  static const char* value()
  {
    return DataType< ::test2::Beam >::value();
  }
  static const char* value(const ::test2::BeamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test2::BeamResponse> should match
// service_traits::MD5Sum< ::test2::Beam >
template<>
struct MD5Sum< ::test2::BeamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test2::Beam >::value();
  }
  static const char* value(const ::test2::BeamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test2::BeamResponse> should match
// service_traits::DataType< ::test2::Beam >
template<>
struct DataType< ::test2::BeamResponse>
{
  static const char* value()
  {
    return DataType< ::test2::Beam >::value();
  }
  static const char* value(const ::test2::BeamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST2_MESSAGE_BEAM_H
