// Generated by gencpp from file test2/MultiplyResponse.msg
// DO NOT EDIT!


#ifndef TEST2_MESSAGE_MULTIPLYRESPONSE_H
#define TEST2_MESSAGE_MULTIPLYRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test2
{
template <class ContainerAllocator>
struct MultiplyResponse_
{
  typedef MultiplyResponse_<ContainerAllocator> Type;

  MultiplyResponse_()
    : MUL(0.0)  {
    }
  MultiplyResponse_(const ContainerAllocator& _alloc)
    : MUL(0.0)  {
  (void)_alloc;
    }



   typedef double _MUL_type;
  _MUL_type MUL;





  typedef boost::shared_ptr< ::test2::MultiplyResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test2::MultiplyResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MultiplyResponse_

typedef ::test2::MultiplyResponse_<std::allocator<void> > MultiplyResponse;

typedef boost::shared_ptr< ::test2::MultiplyResponse > MultiplyResponsePtr;
typedef boost::shared_ptr< ::test2::MultiplyResponse const> MultiplyResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test2::MultiplyResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test2::MultiplyResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test2::MultiplyResponse_<ContainerAllocator1> & lhs, const ::test2::MultiplyResponse_<ContainerAllocator2> & rhs)
{
  return lhs.MUL == rhs.MUL;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test2::MultiplyResponse_<ContainerAllocator1> & lhs, const ::test2::MultiplyResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::test2::MultiplyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test2::MultiplyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test2::MultiplyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test2::MultiplyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test2::MultiplyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test2::MultiplyResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test2::MultiplyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c5ef433cb1dd7d4f8ca73c10abb2759";
  }

  static const char* value(const ::test2::MultiplyResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c5ef433cb1dd7d4ULL;
  static const uint64_t static_value2 = 0xf8ca73c10abb2759ULL;
};

template<class ContainerAllocator>
struct DataType< ::test2::MultiplyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test2/MultiplyResponse";
  }

  static const char* value(const ::test2::MultiplyResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test2::MultiplyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 MUL\n"
;
  }

  static const char* value(const ::test2::MultiplyResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test2::MultiplyResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.MUL);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiplyResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test2::MultiplyResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test2::MultiplyResponse_<ContainerAllocator>& v)
  {
    s << indent << "MUL: ";
    Printer<double>::stream(s, indent + "  ", v.MUL);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST2_MESSAGE_MULTIPLYRESPONSE_H
